tap 'caskroom/cask'
tap 'homebrew/boneyard'
tap 'homebrew/brewdler'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
cask 'java'
brew 'autoconf'
brew 'bash-completion'
brew 'libpng'
brew 'freetype'
brew 'gdbm'
brew 'git'
brew 'gmp'
brew 'gradle'
brew 'jpeg'
brew 'libtiff'
brew 'libtool'
brew 'graphicsmagick'
brew 'groovy'
brew 'heroku'
brew 'hub'
brew 'xz'
brew 'imagemagick'
brew 'oniguruma'
brew 'jq'
brew 'lha'
brew 'openssl'
brew 'libevent'
brew 'lua'
brew 'mas'
brew 'maven'
brew 'memcached', restart_service: true
brew 'mongodb', restart_service: true
brew 'neo4j'
brew 'nkf'
brew 'node'
brew 'nvm'
brew 'pandoc'
brew 'phantomjs'
brew 'pkg-config'
brew 'readline'
brew 'sqlite', args: ['with-functions']
brew 'python'
brew 'postgresql', restart_service: true
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'qt'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-binstubs'
brew 'rbenv-bundler'
brew 'rbenv-gemset'
brew 'reattach-to-user-namespace'
brew 'redis', restart_service: true
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'typesafe-activator'
brew 'vim', args: ['with-lua']
brew 'yarn'
brew 'homebrew/boneyard/rbenv-readline'
brew 'homebrew/boneyard/rsense'
brew 'homebrew/versions/node4-lts'
cask 'alfred'
cask 'atom'
cask 'bathyscaphe'
cask 'burn'
cask 'docker-toolbox'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'genymotion'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'gyazo'
cask 'imageoptim'
cask 'iterm2'
cask 'karabiner'
cask 'karabiner-elements'
cask 'kindle'
cask 'kobito'
cask 'libreoffice'
cask 'licecap'
cask 'rubymine'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'tunnelbear'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'xtrafinder'
mas 'Xcode', id: 497799835
mas 'SpeakLine', id: 441968334
mas 'Keynote', id: 409183694
mas 'iMovie', id: 408981434
mas 'iPhoto', id: 408981381
mas 'Quiver', id: 866773894
mas 'Pages', id: 409201541
mas 'LINE', id: 539883307
mas 'GarageBand', id: 682658836
mas 'BetterSnapTool', id: 417375580
mas 'Numbers', id: 409203825
